### ISSUE TITLE
wrong logrotate when changing log file location

### ISSUE THREAD

**Issue by DamienMure** [earsdown/puppet-tinyproxy#1]
Hi.
First, thank you for this module.
I'm facing a little bug. When I'm using the "logfile" parameter the relocate the log file, logrotate configuration file for debian is not updated.

"/etc/logrotate.d/tinyproxy" still contains a reference to "/var/log/tinyproxy/tinyproxy.log".
So logrotate wont "rotate" anything related to tinyproxy :-( .

Best Regards.

**Comment by earsdown** [comment]
Hey @DamienMure ,

That is indeed a problem. I guess it comes down to the scope of what this module is vs what it isn't. Many organisations would use a separate module to manage logrotate. I'm not sure whether it's wise for a service-specific module like this to attempt to interfere with logrotate directly...

Same with something like SELinux or AppArmor. There's a good chance that if you changed the location of the log file, SELinux/AppArmor would block it, and it's probably beyond the scope of this module to attempt to fix that as well.

May I suggest finding a logrotate module and solving this in your profile module? Or if you want to keep it simple, I'm pretty sure it's just a matter of dropping another file into `/etc/logrotate.d`, and you can copy the tinyproxy logrotate config that comes with the dpkg  (i.e. `/etc/logrotate.d/tinyproxy`).

Good luck.

**Comment by DamienMure** [comment]
Hi.
I agree with you, thank you for the advice.

Regards.
